---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.serviceType | default "ClusterIP" }}
  selector:
    app: {{ include "app.name" . }}
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: http
      {{- if and (eq .Values.app.serviceType "NodePort") .Values.app.nodePort }}
      nodePort: {{ .Values.app.nodePort }}
      {{- end }}
